typography_spectrum: 0.3569
color:
  saturation: 0.6164874
  brandStrength: 0.1577061
  lightness: 1
  brandColors:
    - '#ffffff'
    - '#ff7f00'
    - '#ff4c12'
    - '#ffd7af'
    - '#ff9d3c'
  rhythmicContrast: 0.4014337
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0
analytics:
  twitter: null
  google: null
  facebook: null
name: fvanlint
cta:
  bucket: null
  version: null
  domain: null
favicon: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
title: 'Over Floris van Lint, ontwerper'
description: Visuele communicatie
purpose: []
