name: fvanlint
favicon: null
layout_spectrum: 0
typography_spectrum: 0.3569
title: 'Over Floris van Lint, ontwerper'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#ff7f00'
    - '#ff4c12'
    - '#ffd7af'
    - '#ff9d3c'
  brandStrength: 0.5
  lightness: 0.75
  saturation: 0.5625
  rhythmicContrast: 0.5
purpose:
  - name: awareness
    item: null
    url: null
