analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
layout_spectrum: 0.61897
title: 'Over Floris van Lint, ontwerper'
cta:
  bucket: null
  version: null
  domain: null
color:
  saturation: 0.5625
  brandStrength: 0.375
  rhythmicContrast: 0.5
  brandColors:
    - '#ffffff'
    - '#ff7f00'
    - '#ff4c12'
    - '#ffd7af'
    - '#ff9d3c'
  lightness: 0.75
purpose:
  - name: awareness
    url: null
    item: null
favicon: null
name: fvanlint
typography_spectrum: 0.3569
